server:
    verbosity: 4
    do-daemonize: no
    do-ip6: no
    do-ip4: yes
    root-hints: root.hints

    # module-config: "validator" or "iterator"
    module-config: "iterator"

    # trust-anchor
    auto-trust-anchor-file: "/var/lib/unbound/root.key"

    # access-control
    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: 172.19.0.0/16 allow

    # interface
    interface: 0.0.0.0

    stub-zone:
        name: "example.org."
        stub-addr: 172.19.0.21
